# Generated by Django 4.2.1 on 2023-06-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_circuitos_destinos_turisticos'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
