# Generated by Django 4.2.1 on 2023-06-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_circuitos_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Viajeros',
        ),
    ]
