# Generated by Django 4.2.1 on 2023-06-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0006_rename_circuitos_circuito_rename_pedidos_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajero',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
    ]
